import os
import numpy as np
import pandas as pd

# initial feature set
FEATURE_NAME_LIST = [
    ## pj
    'repo_has_org',
    'repo_age',
    'repo_contributors',
    'repo_subscribers',
    'repo_team_size',
    'repo_open_issue_num',
    'repo_open_delta',
    'repo_closed_issue_time',
    'repo_num_commits_inproject',
    'repo_num_issues_created_inproject',
    'repo_num_issues_created_inproject_closed',
    'repo_num_commits_project_T',
    'repo_num_issues_created_projected_T',
    'repo_num_issues_created_project_closed_T',
    ## issue
    'issue_has_task_type',
    'issue_has_pr',
    'issue_has_conflict',
    'issue_on_rest_day',
    'issue_has_at_tag',
    'issue_has_core_comment',
    'issue_has_other_comment',
    'issue_text_similarity',
    'issue_cleaned_body_len',
    'issue_num_codes',
    'issue_num_urls',
    'issue_num_pics',
    'issue_flesch_reading_ease',
    'issue_desc_positivity',
    'issue_desc_negativity',
    'issue_desc_pos_polarity',
    'issue_desc_subjectivity',
    'issue_num_labels_T',
    'issue_hotness_T',
    'issue_per_event_days_T',
    'issue_num_assignments_T',
    'issue_num_comments_T',
    'issue_mean_comment_size_T',
    'issue_num_referenced_by_T',
    'issue_num_subscribed_by_T',
    'issue_num_actors_T',
    ## devloper
    'author_org',
    'author_core_member',
    'author_newcomer',
    'author_first_issue',
    'author_age',
    'author_followers',
    'author_comments_negative',
    'author_comments_positive',
    'author_num_commits_inproject',
    'author_num_issues_inproject',
    'author_num_issues_closed_inproject',
    'author_num_comments_T',
    'author_issue_closed_days_T',
    'author_num_issue_closed_T',
    'author_num_commits_inproject_T',
    'participant_first_core_member',
    'participant_first_occur',
    'participants_num_T',
    'participants_association_score_T',
    'participant_num_commits_by_actors_T',
    'participant_num_commits_by_unique_actors_T',
    'participant_num_comments_T',
]

# refined feature set
FEATURE_NAME_LIST = [
    'repo_contributors',
    'repo_subscribers',
    'repo_team_size',
    'repo_open_issue_num',
    'repo_open_delta',
    'repo_closed_issue_time',
    'repo_num_commits_project_T',
    'repo_num_issues_created_project_closed_T',
    'issue_has_task_type',
    'issue_has_pr',
    'issue_text_similarity',
    'issue_cleaned_body_len',
    'issue_flesch_reading_ease',
    'issue_num_referenced_by_T',
    'author_core_member',
    'author_newcomer',
    'author_first_issue',
    'author_age',
    'author_comments_negative',
    'author_comments_positive',
    'author_num_commits_inproject',
    'author_issue_closed_days_T',
    'author_num_issue_closed_T',
    'participant_first_core_member',
    'participants_association_score_T',

]
# # Kikas's feature set
# FEATURE_NAME_LIST = [
#     'text_score',
#     'issue_num_comments_T',
#     'issue_num_actors_T',
#     'issue_num_assignments_T',
#     'issue_num_labels_T',
#     'issue_num_mentioned_by_T',
#     'issue_num_referenced_by_T',
#     'issue_num_subscribed_by_T',
#     'issue_mean_comment_size_T',
#     'issue_cleaned_body_len',
#     'author_num_commits_inproject',
#     'author_num_issues_inproject',
#     'author_num_issues_closed_inproject',
#     'participant_num_commits_by_actors_T',
#     'participant_num_commits_by_unique_actors_T',
#     'repo_num_commits_inproject',
#     'repo_num_issues_created_inproject',
#     'repo_num_issues_created_inproject_closed',
#     'repo_num_commits_project_T',
#     'repo_num_issues_created_project_closed_T',
#     'repo_num_issues_created_projected_T',
# ]